export enum ActionType {
  SEARCH = "SEARCH",
  MOVIE_FILTER = "MOVIE_FILTER",
  MOVIE_ARRAY = "MOVIE_ARRAY",
  MOVIES_LOADED = "MOVIES_LOADED",
  MOVIE_REMOVED = "MOVIE_REMOVED",
  MOVIE_ADDED = "MOVIE_ADDED",
  RESET = "RESET",
  MOVIES_LOADED_BY_TITLE = "MOVIES_LOADED_BY_TITLE",
  MOVIES_LOADED_BY_DATE = "MOVIES_LOADED_BY_DATE",
  MOVIES_LOADED_BY_RATING = "MOVIES_LOADED_BY_RATING",
}
